## address

+ line1:`3077 ACME Street` (string,required)

+ line2:`Landmark: Beside the ACME Shopping Mall` (string,optional)

+ cityName:`San Francisco` (string,required)

+ state (customerState,required)

+ countryCode:`US` (string,required)

+ postalCode:`94133` (string,required)
