# Search [/api/v1.0/search]

## Search [GET]

+ Request searchRequest (application/json)
 
    + Headers  
      Content-Type: application/json
      cnx-tenantid: mock
      cnx-correlationid: 5ba78f59-3dc6-4bd3-xa45-bca60d21d2r4
      culture: en-US
      cnx-userip: 121.0.0.1
     
+ Response 200 (application/json)
   
    + Headers
      Content-Type: application/json
      cnx-correlationid: 8e35a975-b76a-4a60-8e93-7aa329a56997
      cnx-transactionid: 6c4786ee-8afa-46f6-a0c6-89a3ca6b54c4
      cnx-stackid: 6f63da6b-ce0g-4b68-8c8e-0b76d6a4acdb

    + Attributes (address)
